# Generated by Django 5.1 on 2024-08-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nutrient", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nutrient",
            name="food_weight_type",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="nutrient",
            name="nutrition_content_standard_type",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
