# Generated by Django 5.1 on 2024-08-10 12:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nutrient", "0003_photoresponsecache"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PhotoResponseCache",
            new_name="ImageResponseCache",
        ),
    ]
