# Generated by Django 5.1 on 2024-08-10 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nutrient", "0006_userfood_userprofile_userweight"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfood",
            name="user_profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consumed_foods",
                to="nutrient.userprofile",
            ),
        ),
    ]
